[package]
name = "inve-block-buffer"
version = "0.0.1"
license = "Apache-2.0"
description = "Buffer type for block processing of data."
keywords = ["block", "buffer"]
categories = ["cryptography", "no-std"]
edition = "2021"

[dependencies]
generic-array = "0.14"
